const mockGalleryCardData = [
  {
    id: 'biking-l2UC5xW',
    description: 'shot taken in streets of shibuya',
    title: 'Biking',
    artist: 'Arthur',
    datePosted: 'November 12, 2021',
    tags: ['style-request'],
    topic: 'fit-check',
    assets: ['https://www.themodestman.com/wp-content/uploads/2019/09/NYC_April_2010_Brock_Eric_Khoi-32-650x880.jpg', 'https://images.unsplash.com/photo-1636405719459-724ea267d845?w=500&h=500&fit=crop'],
    views: 149,
    likes: 3199,
  },
  {
    id: 'NVTMTdNaOoE1',
    description: '',
    title: 'Walking through japan',
    artist: '疫よか',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'fit-check',
    assets: ['https://i.pinimg.com/564x/28/2b/07/282b078d6ef40b600f0d9a10a55b6d2d.jpg'],
    views: 2313,
    likes: 5812,
  },
  {
    id: 'FspWyjwMhyFr',
    description: '',
    title: 'burgir',
    artist: 'hasbullah',
    datePosted: 'November 12, 2021',
    tags: ['style-style-request', 'fit-check'],
    topic: 'fit-check',
    assets: ['https://i.styleoholic.com/2017/11/Black-beanie-bomber-jacket-t-shirt-trouserss-and-oxford-shoes.jpg'],
    views: 1321,
    likes: 3145,
  },
  {
    id: 'IeCTYvf0gAId',
    description: '',
    title: 'waves',
    artist: 'lothbrok',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'fit-check',
    assets: ['https://www.themodestman.com/wp-content/uploads/2019/09/Brown-Sweater-and-Blue-Jeans--650x880.jpg', 'https://images.unsplash.com/photo-1636207608470-dfedb46c2380?w=500&h=500&fit=crop'],
    views: 41,
    likes: 31,
  },
  {
    id: 'ge1fDLGGmdGX',
    description: '',
    title: 'spinetastic',
    artist: 'eren',
    datePosted: 'November 12, 2021',
    tags: ['style-style-request', 'fit-check'],
    topic: 'fit-check',
    assets: ['https://n5b7j3m9.rocketcdn.me/wp-content/uploads/2021/01/15-375x500.png'],
    views: 186,
    likes: 5223,
  },
  {
    id: 'K87vqYNTon7b',
    description: '',
    title: 'Retro',
    artist: 'Hans. & Taebz',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'fit-check',
    assets: ['https://www.youtube.com/watch?v=Z6jLSELzeJs'],
    views: 6636,
    likes: 4124,
    type: 'video',
  },
  {
    id: 'K87vqYNTon7b',
    description: '',
    title: 'Retro',
    artist: 'Hans. & Taebz',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'style-request',
    assets: ['Looking for a chill casual style for a date'],
    views: 6636,
    likes: 4124,
    type: 'text',
  },
  {
    id: 'IAN4NMukeU1e',
    description: '',
    title: 'sunset drive',
    artist: 'molken',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'fit-check',
    assets: ['https://www.outfit-styles.com/wp-content/uploads/2020/04/Outfit-Idea-for-Women.jpg'],
    views: 41,
    likes: 32,
    comments: 3,
  },
  {
    id: 'roOO8yGfpjbd',
    description: '',
    title: 'spinetastic',
    artist: 'eren',
    datePosted: 'November 12, 2021',
    tags: ['style-style-request', 'fit-check'],
    topic: 'fit-check',
    assets: ['https://images.unsplash.com/photo-1636927743238-4052967c20e4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=665&q=80'],
    views: 186,
    likes: 5223,
  },
  {
    id: 'IAN4NMukeU1e',
    description: '',
    title: 'sunset drive',
    artist: 'molken',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'fit-check',
    assets: ['https://static.highsnobiety.com/thumbor/A4BVZez3aDtlNeBNOBRV7MoMIWM=/1600x2400/static.highsnobiety.com/wp-content/uploads/2018/11/08191043/best-streetwear-brands-women-06.jpg'],
    views: 41,
    likes: 32,
  },
  {
    id: 'K87vqYNTon7b',
    description: '',
    title: 'Retro',
    artist: 'Hans. & Taebz',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'style-request',
    assets: ['Does this fit make sense?'],
    views: 6636,
    likes: 4124,
    type: 'text',
  },
  {
    id: 'K87vqYNTon7b',
    description: '',
    title: 'Retro',
    artist: 'Hans. & Taebz',
    datePosted: 'November 12, 2021',
    tags: [],
    topic: 'discussion',
    assets: ['What do you guys think about the state of fashion?'],
    views: 6636,
    likes: 4124,
    type: 'text',
  },
];

export default mockGalleryCardData;
